# Generated by Django 4.2 on 2025-04-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contrato_empresa_detalhescontrato_contrato_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosVisaoGerencialCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_empresa', models.CharField(default='all', max_length=50, verbose_name='Empresa')),
                ('filtro_contrato', models.CharField(default='all', max_length=50, verbose_name='Contrato')),
                ('filtro_periodo', models.CharField(default='30', max_length=10, verbose_name='Período')),
                ('dados_json', models.TextField(verbose_name='Dados em JSON')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Cache de Dados da Visão Gerencial',
                'verbose_name_plural': 'Cache de Dados da Visão Gerencial',
                'unique_together': {('filtro_empresa', 'filtro_contrato', 'filtro_periodo')},
            },
        ),
    ]
