# Generated by Django 5.1.7 on 2025-04-08 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('acao', models.CharField(choices=[('INCLUSAO', 'Inclusão'), ('EDICAO', 'Edição'), ('EXCLUSAO', 'Exclusão'), ('IMPORTACAO', 'Importação')], max_length=20, verbose_name='Ação')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('usuario', models.CharField(max_length=255, verbose_name='Usuário')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço IP')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Log de Produto',
                'verbose_name_plural': 'Logs de Produtos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
