# Generated by Django 4.2 on 2025-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_fornecedor_produto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cargo_contato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Contato'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Fornecedor'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='email_secundario',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Secundário'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='pessoa_contato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone_secundario',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Secundário'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail Principal'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.TextField(verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone Principal'),
        ),
    ]
