# Generated by Django 4.2 on 2025-04-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_fornecedor_cargo_contato_fornecedor_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='dia_pedido_recorrente',
            field=models.PositiveIntegerField(blank=True, help_text='Dia do mês em que o pedido deve ser gerado (1-31)', null=True, verbose_name='Dia do Pedido Recorrente'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='gerar_pedido_recorrente',
            field=models.BooleanField(default=False, verbose_name='Gerar Pedido Recorrente'),
        ),
    ]
