# Generated by Django 4.2 on 2025-04-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_fornecedor_dia_pedido_recorrente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='dia_pedido_recorrente',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='gerar_pedido_recorrente',
        ),
    ]
