# Generated by Django 4.2 on 2025-05-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_remove_fornecedor_dia_pedido_recorrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='dia_pedido_recorrente',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês para gerar pedidos recorrentes (1-31)', null=True, verbose_name='Dia do Pedido Recorrente'),
        ),
    ]
