# Generated by Django 4.2 on 2025-05-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_fornecedor_dia_pedido_recorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='tipo_fornecedor',
            field=models.CharField(choices=[('FIXO', 'Fixo'), ('ESPORADICO', 'Esporádico')], default='FIXO', max_length=10, verbose_name='Tipo do Fornecedor'),
        ),
    ]
