# Generated by Django 5.1.7 on 2025-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa de Cancelamento'),
        ),
    ]
