# Generated by Django 5.1.7 on 2025-03-26 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('alteracao_status', 'Alteração de Status'), ('edicao', 'Edição de Dados'), ('exclusao', 'Exclusão')], max_length=20, verbose_name='Ação')),
                ('status_anterior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Novo Status')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pedidos.pedido', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Pedido',
                'verbose_name_plural': 'Logs de Pedidos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
