# Generated by Django 5.1.7 on 2025-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedidolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='recebido_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recebido por'),
        ),
    ]
