# Generated by Django 4.2 on 2025-04-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_fornecedor_dia_pedido_recorrente_and_more'),
        ('pedidos', '0006_pedido_recebido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='produtos.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recorrentes', to='pedidos.pedido', verbose_name='Pedido Original'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_recorrente',
            field=models.BooleanField(default=False, verbose_name='Pedido Recorrente'),
        ),
    ]
