# Generated by Django 4.2 on 2025-04-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_orcamento_dia_pedido_recorrente_and_more'),
        ('pedidos', '0007_pedido_fornecedor_pedido_pedido_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_original',
        ),
        migrations.AddField(
            model_name='pedido',
            name='orcamento_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_gerados', to='orcamentos.orcamento'),
        ),
    ]
