# Generated by Django 4.2 on 2025-05-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_fornecedor_dia_pedido_recorrente'),
        ('pedidos', '0008_remove_pedido_fornecedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='orcamento_origem',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='produtos.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recorrentes', to='pedidos.pedido', verbose_name='Pedido Original'),
        ),
    ]
