# Generated by Django 4.2 on 2025-05-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_remove_pedido_orcamento_origem_pedido_fornecedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_nfe', models.CharField(max_length=44, unique=True, verbose_name='Chave da NFe')),
                ('numero_nfe', models.CharField(max_length=20, verbose_name='Número da NFe')),
                ('data_emissao', models.DateTimeField(verbose_name='Data de Emissão')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('razao_social_emitente', models.CharField(max_length=255, verbose_name='Razão Social do Emitente')),
                ('cnpj_emitente', models.CharField(max_length=14, verbose_name='CNPJ do Emitente')),
                ('xml_completo', models.TextField(blank=True, null=True, verbose_name='XML Completo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_emissao'],
            },
        ),
    ]
