# Generated by Django 4.2 on 2025-05-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_notafiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída/Entrega'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='destinatario_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ do Destinatário'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='destinatario_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Destinatário'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='informacoes_complementares',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Complementares'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='natureza_operacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Natureza da Operação'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='serie',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Série'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Desconto'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Frete'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_impostos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor dos Impostos'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_outras_despesas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Outras Despesas'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_produtos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor dos Produtos'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='valor_seguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Seguro'),
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(verbose_name='Número do Item')),
                ('codigo_produto', models.CharField(max_length=60, verbose_name='Código do Produto')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('ncm', models.CharField(blank=True, max_length=8, null=True, verbose_name='NCM')),
                ('cfop', models.CharField(blank=True, max_length=4, null=True, verbose_name='CFOP')),
                ('unidade', models.CharField(max_length=6, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Desconto')),
                ('num_pedido', models.CharField(blank=True, max_length=60, null=True, verbose_name='Número do Pedido no Item')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.notafiscal', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Item da Nota Fiscal',
                'verbose_name_plural': 'Itens da Nota Fiscal',
                'ordering': ['numero_item'],
            },
        ),
    ]
