# Generated by Django 4.2 on 2025-05-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_notafiscal_data_saida_notafiscal_destinatario_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnotafiscal',
            name='icms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alíquota ICMS (%)'),
        ),
        migrations.AddField(
            model_name='itemnotafiscal',
            name='ipi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alíquota IPI (%)'),
        ),
    ]
