# Generated by Django 4.2 on 2025-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_itemnotafiscal_icms_itemnotafiscal_ipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='previsao_entrega_fornecedor',
            field=models.DateField(blank=True, help_text='Data prevista de entrega informada pelo fornecedor', null=True, verbose_name='Previsão de Entrega (Fornecedor)'),
        ),
    ]
