# Generated by Django 4.2 on 2025-05-06 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0013_add_previsao_entrega_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovanteEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Anexar comprovante de entrega do pedido (PDF, imagem, etc.)', upload_to='comprovantes_entrega/%Y/%m/', verbose_name='Arquivo do Comprovante')),
                ('descricao', models.CharField(blank=True, help_text='Descrição opcional do comprovante', max_length=255, null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes_entrega', to='pedidos.pedido', verbose_name='Pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que enviou')),
            ],
            options={
                'verbose_name': 'Comprovante de Entrega',
                'verbose_name_plural': 'Comprovantes de Entrega',
                'ordering': ['-data_upload'],
            },
        ),
    ]
