# Generated by Django 5.1.7 on 2025-03-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='escola',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote'),
        ),
    ]
