# Generated by Django 5.1.7 on 2025-03-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_escola_empresa_escola_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor máximo permitido por pedido', max_digits=10, verbose_name='Orçamento (R$)'),
        ),
    ]
