# Generated by Django 5.1.7 on 2025-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_supervisor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='data_validade_budget',
            field=models.DateField(blank=True, help_text='Data limite para utilização do orçamento', null=True, verbose_name='Validade do Orçamento'),
        ),
    ]
