# Generated by Django 5.1.7 on 2025-04-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_escola_data_validade_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscolaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=255, verbose_name='Nome da Escola/Contrato')),
                ('acao', models.CharField(choices=[('INCLUSAO', 'Inclusão'), ('EDICAO', 'Edição'), ('EXCLUSAO', 'Exclusão'), ('IMPORTACAO', 'Importação')], max_length=20, verbose_name='Ação Realizada')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('usuario', models.CharField(max_length=150, verbose_name='Usuário')),
                ('ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='Endereço IP')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Log de Escola/Contrato',
                'verbose_name_plural': 'Logs de Escolas/Contratos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
