# Generated by Django 4.2 on 2025-04-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0006_escolalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Anterior (R$)')),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Novo (R$)')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('usuario', models.CharField(max_length=150, verbose_name='Usuário')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_budget', to='escolas.escola')),
            ],
            options={
                'verbose_name': 'Histórico de Orçamento',
                'verbose_name_plural': 'Históricos de Orçamento',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
