# Generated by Django 4.2 on 2025-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_itemorcamento_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_entrega_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista de Entrega'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('avista', 'À Vista'), ('30dias', '30 Dias'), ('60dias', '60 Dias'), ('90dias', '90 Dias'), ('parcelado', 'Parcelado'), ('outros', 'Outros')], default='avista', max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
