# Generated by Django 4.2 on 2025-04-30 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orcamentos', '0003_orcamento_data_entrega_prevista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Justificativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificativa_aprovacao', to='orcamentos.orcamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Justificativa de Aprovação',
                'verbose_name_plural': 'Justificativas de Aprovação',
            },
        ),
    ]
