# Generated by Django 4.2 on 2025-04-30 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0004_justificativaaprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='dia_pedido_recorrente',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do Pedido Recorrente'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pedido_recorrente',
            field=models.BooleanField(default=False, verbose_name='Gerar Pedido Recorrente'),
        ),
    ]
