# Generated by Django 4.2 on 2025-05-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_orcamento_dia_pedido_recorrente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='dia_pedido_recorrente',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='pedido_recorrente',
        ),
    ]
